server:
  port: "8080"
  host: "localhost"
  env: "production"
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "amkodor_db"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300

jwt:
  secret: "amkodor-production-secret-key-change-me"
  expire_hours: 24
  refresh_expire_hours: 168

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 300

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file: "logs/app.log"

upload:
  max_size: 10485760
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
  path: "./uploads/"

export:
  path: "./exports/"
  temp_path: "./exports/temp/"
  max_age_days: 7

ssis:
  package_name: "AmkodorExport"
  config_table: "ssis_configuration"
  log_table: "ssis_log"